spring.application.name=news
server.port=8080

# API Keys
gnews.key=31ba08fb7366805896e08efb15a5a962
unsplash.key=nObjxRsUggb8x5_zsNI9I96K29qpTBnigQiGYnNN2BY


# CORS
cors.allowed.origins=http://localhost:3000